console.log("controllers/index.js");//blup

// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import OrdersController from "./orders_controller"
application.register("orders", OrdersController)
import IsOnlineController from "./is_online_controller"
application.register("is_online", IsOnlineController)
import QrCodeScannerController from "./qr_code_scanner_controller"
application.register("qr_code_scanner", QrCodeScannerController)
import FileFiledController from "./file_field_controller"
application.register("file_field", FileFiledController)

import PwaDeviceFormController from "./pwa/device_form_controller"
application.register("pwa_device_form", PwaDeviceFormController)
import PwaSyncController from "./pwa/sync_controller"
application.register("pwa_sync", PwaSyncController)
